server:
  port: 8083

spring:
  application:
    name: login-service

  datasource:
    # url: jdbc:mysql://192.168.71.71:3307/LoginDB
    url: jdbc:mysql://localhost:3307/LoginDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus

    metrics:
        enable:
            http:
                server:
                    requests: true
        distribution:
            percentiles:
                "[http.server.requests]": 0.95

eureka:
  client:
    service-url:
      # defaultZone: http://192.168.71.71:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
